---
- hosts: localhost

  tasks:
  - name: Create group member
    hawkular_alerts_group_member:
      hawkular_api_hostname: 'hawkular-hostname.example.com'
      hawkular_api_port: 443
      hawkular_api_auth_token: '******'
      tenant: '_system'
      group_id: 'test_group-01'
      id: 'member1'
      name: 'Member One'
      description: 'the first member of test_group-01 trigger'
      data_id_map:
        'test_condition': 'test_condition_member1'
      tags:
        nodename: node01
      state: 'present'
    register: result

  - debug: var=result
